"""
Falsification test stubs for the artifact-prediction timestamp contract.
Generated by falsification audit 2026-05-19.

F-1 (HARD): Implementation fix not committed — branch-hygiene finding, not a code test.
F-4 (SOFT): No test verifies timestamp propagation — stubs below.
"""

from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

from conftest import make_manager, MANAGER_BASE_CONFIG, MANAGER_PARTITION, ARTIFACT_TS

ARTIFACT_PATH = Path(f"dummy_artifacts_path/calibration_model_{ARTIFACT_TS}.pkl")


def _make():
    mgr = make_manager(MANAGER_BASE_CONFIG.copy(), MANAGER_PARTITION)
    mgr._model_path.get_latest_model_artifact_path = lambda run_type: ARTIFACT_PATH
    return mgr


class TestTimestampPropagation:
    """
    Verify that _evaluate_model_artifact and _forecast_model_artifact
    extract the artifact timestamp and persist it in config, per ADR-052.
    """

    @pytest.mark.parametrize("method,setup_patches,kwargs", [
        (
            "_evaluate_model_artifact",
            {"_setup_model_and_data": (MagicMock(), MagicMock()),
             "_generate_predictions": []},
            {"eval_type": "standard"},
        ),
        (
            "_forecast_model_artifact",
            None,
            {},
        ),
    ])
    def test_persists_artifact_timestamp_in_config(self, method, setup_patches, kwargs):
        mgr = _make()

        if method == "_forecast_model_artifact":
            with patch.object(mgr, "_setup_model_and_data") as mock_setup:
                mock_model = MagicMock()
                mock_model.predict.return_value = MagicMock()
                mock_setup.return_value = (mock_model, MagicMock())
                getattr(mgr, method)(**kwargs)
        else:
            with patch.object(mgr, "_setup_model_and_data") as mock_setup, \
                 patch.object(mgr, "_generate_predictions") as mock_preds:
                mock_setup.return_value = setup_patches["_setup_model_and_data"]
                mock_preds.return_value = setup_patches["_generate_predictions"]
                getattr(mgr, method)(**kwargs)

        assert mgr.config["timestamp"] == ARTIFACT_TS, (
            f"Expected '{ARTIFACT_TS}' from artifact stem, "
            f"got '{mgr.config.get('timestamp')}'"
        )

    def test_timestamp_is_not_datetime_now(self):
        from datetime import datetime

        mgr = _make()
        before = datetime.now().strftime("%Y%m%d_%H%M%S")

        with patch.object(mgr, "_setup_model_and_data") as mock_setup, \
             patch.object(mgr, "_generate_predictions") as mock_preds:
            mock_setup.return_value = (MagicMock(), MagicMock())
            mock_preds.return_value = []
            mgr._evaluate_model_artifact(eval_type="standard")

        after = datetime.now().strftime("%Y%m%d_%H%M%S")
        ts = mgr.config["timestamp"]

        assert ts == ARTIFACT_TS, (
            f"Timestamp '{ts}' looks like datetime.now() "
            f"(wall clock range: {before}–{after}), "
            f"not artifact timestamp '{ARTIFACT_TS}'"
        )
