"""Falsification probes for the PR-1 SOLID / screaming-architecture reorg claim.

Generated by ``/falsify`` against the claim "the reorg adheres to SRP/OCP/LSP/ISP/DIP +
REP/CCP/CRP/ADP/SDP/SAP + screaming architecture".

Two kinds of test live here:

* **Guards that PASS** — properties the reorg genuinely achieves and that we want to lock
  in against regression (currently: ADP acyclicity).
* **Strict-xfail probes** — principle gaps that are *real in the current (PR-1) tree*.
  They are ``xfail(strict=True)`` so they (a) do not break the green suite, (b) document
  the exact gap, and (c) **ratchet**: the moment the gap is closed (e.g. PR-2 removes the
  pandas dependency), the test unexpectedly passes and strict-xfail turns it into a hard
  failure — forcing whoever closed it to convert the probe into a permanent guard.

Findings (see the /falsify report):
  P1 DIP  — model logic still imports concrete pandas (deferred to PR-2, #53-#56).  HARD.
  P2 OCP  — adding a model modifies catalog.py + ALGORITHM_GENOMES (known C-19).     SOFT.
  P4 SCREAM — frames/pooling.py is pandas->numpy windowing, not a Frame boundary.    SOFT.
  P5 ADP  — the model-layer import graph is acyclic.                                 SURVIVED.
"""

import ast
import collections
import pathlib

import pytest

PKG = pathlib.Path(__file__).resolve().parent.parent / "views_baseline"
MODEL = PKG / "model"


def _import_graph():
    """Module-level intra-package import graph (node -> set of imported modules)."""
    mods = {
        ".".join(p.with_suffix("").relative_to(PKG.parent).parts): p
        for p in PKG.rglob("*.py")
    }
    graph = collections.defaultdict(set)
    for mod, p in mods.items():
        src = mod[: -len(".__init__")] if mod.endswith(".__init__") else mod
        for node in ast.walk(ast.parse(p.read_text())):
            if (
                isinstance(node, ast.ImportFrom)
                and node.module
                and node.module.startswith("views_baseline")
            ):
                graph[src].add(node.module)
    return graph


def _has_cycle(graph):
    WHITE, GRAY, BLACK = 0, 1, 2
    color = collections.defaultdict(int)
    cycles = []

    def visit(u, path):
        color[u] = GRAY
        path.append(u)
        for v in graph.get(u, ()):
            vn = v[: -len(".__init__")] if v.endswith(".__init__") else v
            if color[vn] == GRAY:
                cycles.append(path[path.index(vn):] + [vn])
            elif color[vn] == WHITE and vn in graph:
                visit(vn, path)
        color[u] = BLACK
        path.pop()

    for u in list(graph):
        if color[u] == WHITE:
            visit(u, [])
    return cycles


# ---------------------------------------------------------------------------
# P5 (SURVIVED) — permanent guard: the reorg's import graph must stay acyclic (ADP).
# ---------------------------------------------------------------------------
def test_adp_model_layer_import_graph_is_acyclic():
    cycles = _has_cycle(_import_graph())
    assert cycles == [], f"ADP violated — import cycle(s): {cycles}"


# ---------------------------------------------------------------------------
# P1 (RESOLVED in PR-2 S6-S9, #53-#56) — high-level model logic depends on the FeatureFrame
# abstraction, not concrete pandas. pandas is confined to the lazy import inside
# `to_feature_frame` (frames/input.py); every other model module imports pandas only under
# `if TYPE_CHECKING:` (type hints), never at runtime. Permanent guard (was strict-xfail in
# PR-1; flipped when the numpy-on-FeatureFrame port landed).
# ---------------------------------------------------------------------------
def _has_runtime_module_level_pandas_import(path):
    """True if the module imports pandas at module scope (not under TYPE_CHECKING, not in a
    function body). Nested imports (inside `if TYPE_CHECKING:` or inside a def) are excluded."""
    for node in ast.parse(path.read_text()).body:  # top-level statements only
        if isinstance(node, ast.Import):
            if any(a.name.split(".")[0] == "pandas" for a in node.names):
                return True
        elif isinstance(node, ast.ImportFrom):
            if node.module and node.module.split(".")[0] == "pandas":
                return True
    return False


def test_dip_model_layer_has_no_runtime_pandas_import():
    offenders = [
        p.relative_to(PKG).as_posix()
        for p in MODEL.rglob("*.py")
        if _has_runtime_module_level_pandas_import(p)
    ]
    assert offenders == [], f"DIP: runtime module-level pandas import in: {offenders}"


# ---------------------------------------------------------------------------
# P2 (SOFT, OCP) — adding a model should not require modifying the catalog (known C-19).
# The catalog hardcodes a model registry, so a new model is not a pure extension.
# ---------------------------------------------------------------------------
@pytest.mark.xfail(
    strict=True,
    reason="OCP: catalog hardcodes the model registry (C-19 three-registry); "
    "adding a model modifies catalog.py + ALGORITHM_GENOMES",
)
def test_ocp_catalog_does_not_hardcode_model_registry():
    tree = ast.parse((MODEL / "catalog.py").read_text())
    hardcoded = 0
    for node in ast.walk(tree):
        # the `self.models = { "ZeroModel": ..., ... }` dispatch dict
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Dict):
            hardcoded = max(hardcoded, len(node.value.keys))
    assert hardcoded == 0, (
        f"OCP: catalog hardcodes {hardcoded} model entries (modification surface)"
    )


# ---------------------------------------------------------------------------
# P4 (RESOLVED in PR-2 S6, #53) — every module under frames/ is about the views-frames
# boundary. window_pool now consumes a FeatureFrame (frame-native), so this is a permanent
# guard (was strict-xfail during PR-1; flipped when the port landed).
# ---------------------------------------------------------------------------
def test_screaming_frames_package_is_only_about_frames():
    non_frame = [
        p.relative_to(PKG).as_posix()
        for p in (MODEL / "frames").glob("*.py")
        if p.name != "__init__.py" and "views_frames" not in p.read_text()
    ]
    assert non_frame == [], f"screaming: frames/ modules not about views_frames: {non_frame}"
