"""
Falsification test stubs for the artifact-prediction timestamp contract.
Generated by falsification audit 2026-05-19.

F-1 (HARD): Implementation fix not committed — branch-hygiene finding, not a code test.
F-4 (SOFT): No test verifies timestamp propagation — stubs below.
"""

import pytest
from pathlib import Path
from unittest.mock import patch, MagicMock

from conftest import make_manager

ARTIFACT_TS = "20260101_120000"
ARTIFACT_PATH = Path(f"dummy_artifacts_path/calibration_model_{ARTIFACT_TS}.pkl")

BASE_CONFIG = {
    "run_type": "calibration",
    "algorithm": "LocfModel",
    "level": "pgm",
    "time_steps": 36,
    "targets": ["synth_target"],
    "regression_targets": ["synth_target"],
    "regression_point_metrics": ["MSE"],
}

PARTITION = {"test": (120, 125)}


def _make():
    mgr = make_manager(BASE_CONFIG.copy(), PARTITION)
    mgr._model_path.get_latest_model_artifact_path = lambda run_type: ARTIFACT_PATH
    return mgr


class TestTimestampPropagation:
    """
    Verify that _evaluate_model_artifact and _forecast_model_artifact
    extract the artifact timestamp and persist it in config, per ADR-052.
    """

    def test_evaluate_persists_artifact_timestamp_in_config(self):
        mgr = _make()

        with patch.object(mgr, "_setup_model_and_data") as mock_setup, \
             patch.object(mgr, "_generate_predictions") as mock_preds:
            mock_setup.return_value = (MagicMock(), MagicMock())
            mock_preds.return_value = []
            mgr._evaluate_model_artifact(eval_type="standard")

        assert mgr.config["timestamp"] == ARTIFACT_TS, (
            f"Expected '{ARTIFACT_TS}' from artifact stem, "
            f"got '{mgr.config.get('timestamp')}'"
        )

    def test_forecast_persists_artifact_timestamp_in_config(self):
        mgr = _make()

        with patch.object(mgr, "_setup_model_and_data") as mock_setup:
            mock_model = MagicMock()
            mock_model.predict.return_value = MagicMock()
            mock_setup.return_value = (mock_model, MagicMock())
            mgr._forecast_model_artifact()

        assert mgr.config["timestamp"] == ARTIFACT_TS, (
            f"Expected '{ARTIFACT_TS}' from artifact stem, "
            f"got '{mgr.config.get('timestamp')}'"
        )

    def test_timestamp_is_not_datetime_now(self):
        from datetime import datetime

        mgr = _make()
        before = datetime.now().strftime("%Y%m%d_%H%M%S")

        with patch.object(mgr, "_setup_model_and_data") as mock_setup, \
             patch.object(mgr, "_generate_predictions") as mock_preds:
            mock_setup.return_value = (MagicMock(), MagicMock())
            mock_preds.return_value = []
            mgr._evaluate_model_artifact(eval_type="standard")

        after = datetime.now().strftime("%Y%m%d_%H%M%S")
        ts = mgr.config["timestamp"]

        assert ts == ARTIFACT_TS, (
            f"Timestamp '{ts}' looks like datetime.now() "
            f"(wall clock range: {before}–{after}), "
            f"not artifact timestamp '{ARTIFACT_TS}'"
        )
